using ParingManager.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ParingManager.Models
{
    public class CharacterModel
    {
        List<Character> characters;
        public ClassModel classes;        

        public CharacterModel()
        {
            characters = new List<Character>();
            classes = new ClassModel();

            LoadCharacters();
        }

        private void LoadCharacters()
        {
            List<Character> list = new List<Character>();

            list.Add(new Parent { Name = CharacterNames.Avatar, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.Supportive), StartingClass = classes.GetClassByClassName(ClassNames.DarkPrincess), AlternateClass = new BaseClass(), AlternateClassB = new BaseClass(), InheritanceA = new BaseClass(), InheritanceB = new BaseClass(), FriendshipSupportList = "", FriendshipSupports = new List<Character>(), RomanticSupportsList = "", RomanticSupports = new List<Character>(), AvailableChildName = CharacterNames.Kana, AvailableChild = new Child() });
            list.Add(new Child { Name = CharacterNames.Kana, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.DraconicHex), StartingClass = classes.GetClassByClassName(ClassNames.DarkPrincess), AlternateClass = new BaseClass(), AlternateClassB = new BaseClass(), InheritanceA = new BaseClass(), InheritanceB = new BaseClass(), RomanticSupports = new List<Character>(), RomanticSupportsList = "", FriendshipSupports = new List<Character>(), FriendshipSupportList = "", PrimaryParent = GetCharacterByCharacterName(CharacterNames.Avatar), PrimaryParentName = "Avatar" });
            list.Add(new Parent { Name = CharacterNames.Azura, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.HealingDescant), StartingClass = classes.GetClassByClassName(ClassNames.Songstress), AlternateClass = classes.GetClassByClassName(ClassNames.SkyKnight), AlternateClassB = new BaseClass(), InheritanceA = classes.GetClassByClassName(ClassNames.Troubadour), InheritanceB = classes.GetClassByClassName(ClassNames.WyvernRider), AvailableChild = new Child(), AvailableChildName = CharacterNames.Shigure, FriendshipSupportList = "Hinoka, Sakura, Elise, Avatar", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Azama, Hayato, Hinata, Kaden, Ryoma, Saizo, Subaki, Takumi, Arthur, Benny, Keaton, Laslow, Leo, Niles, Odin, Xander, Avatar, Jakob, Kaze, Silas", RomanticSupports = new List<Character>() });
            list.Add(new Character { Name = CharacterNames.Felicia, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.DevotedPartner), StartingClass = classes.GetClassByClassName(ClassNames.Troubadour), AlternateClass = classes.GetClassByClassName(ClassNames.Mercenary), AlternateClassB = new BaseClass(), InheritanceA = new BaseClass(), InheritanceB = classes.GetClassByClassName(ClassNames.Samurai), FriendshipSupportList = "Hana, Peri, Flora, Avatar", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Azama, Hayato, Hinata, Kaden, Ryoma, Saizo, Takumi, Arthur, Benny, Keaton, Laslow, Leo, Niles, Odin, Xander, Avatar, Jakob, Kaze, Silas", RomanticSupports = new List<Character>() });
            list.Add(new Parent { Name = CharacterNames.Jakob, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.EvasivePartner), StartingClass = classes.GetClassByClassName(ClassNames.Troubadour), AlternateClass = classes.GetClassByClassName(ClassNames.Cavelier), InheritanceA = new BaseClass(), InheritanceB = classes.GetClassByClassName(ClassNames.Ninja), FriendshipSupportList = "Takumi, Avatar, Gunter, Silas", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Hana, Hinkoka, Kagero, Oboro, Orochi, Rinkah, Sakura, Setsuna, Beruka, Camilla, Charlotte, Effie, Elise, Nyx, Peri, Selena, Avatar, Azura, Felicia, Mozu", RomanticSupports = new List<Character>(), AvailableChild = new Child(), AvailableChildName = CharacterNames.Dwyer });
            list.Add(new Child { Name = CharacterNames.Dwyer, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.BornSteward), StartingClass = classes.GetClassByClassName(ClassNames.Troubadour), AlternateClass = classes.GetClassByClassName(ClassNames.Cavelier), InheritanceA = new BaseClass(), InheritanceB = new BaseClass(), FriendshipSupportList = "Asugi, Kiragi, Percy, Avatar, Jakob", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Caeldori, Mitama, Rhajat, Selkie, Nina, Ophelia, Soliel, Velouria, Avatar, Kana, Sophie, Midori", RomanticSupports = new List<Character>(), PrimaryParent = new Parent(), PrimaryParentName = CharacterNames.Jakob });
            list.Add(new Parent { Name = CharacterNames.Kaze, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.MiraculousSave), StartingClass = classes.GetClassByClassName(ClassNames.Ninja), AlternateClass = classes.GetClassByClassName(ClassNames.Samurai), InheritanceA = classes.GetClassByClassName(ClassNames.Cavelier), InheritanceB = classes.GetClassByClassName(ClassNames.Mercenary), AvailableChildName = "Midori", AvailableChild = new Child(), FriendshipSupportList = "Saizo, Xander, Avatar, Silas", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Hana, Hinoka, Kagero, Oboro, Orochi, Rinkah, Sakura, Setsuna, Beruka, Camilla, Charlotte, Effie, Elise, Nyx, Peri, Selena, Avatar, Azura, Felicia, Mozu", RomanticSupports = new List<Character>() });
            list.Add(new Child { Name = CharacterNames.Midori, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.LuckyCharm), StartingClass = classes.GetClassByClassName(ClassNames.Apothecary), AlternateClass = classes.GetClassByClassName(ClassNames.Ninja), InheritanceA = new BaseClass(), InheritanceB = new BaseClass(), PrimaryParentName = CharacterNames.Kaze, PrimaryParent = new Parent(), FriendshipSupportList = "Selkie, Ophelia, Avatar, Kana", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Asugi, Hisame, Kiragi, Shiro, Forrest, Ignatius, Percy, Siegbert, Avatar, Kana, Dwyer, Shigure", RomanticSupports = new List<Character>() });
            list.Add(new Child { Name = CharacterNames.Shigure, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.PerfectPitch), StartingClass = classes.GetClassByClassName(ClassNames.SkyKnight), AlternateClass = classes.GetClassByClassName(ClassNames.Troubadour), InheritanceA = new BaseClass(), InheritanceB = new BaseClass(), PrimaryParentName = CharacterNames.Azura, PrimaryParent = new Parent(), FriendshipSupportList = "Hisame, Forrest, Avatar", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Caeldori, Mitama, Rhajat, Selkie, Nina, Ophelia, Soliel, Velouria, Avatar, Kana, Sophie, Midori", RomanticSupports = new List<Character>() });
            list.Add(new Parent { Name = CharacterNames.Silas, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.VowOfFriendship), StartingClass = classes.GetClassByClassName(ClassNames.Cavelier), AlternateClass = classes.GetClassByClassName(ClassNames.Mercenary), InheritanceA = classes.GetClassByClassName(ClassNames.Ninja), InheritanceB = classes.GetClassByClassName(ClassNames.Samurai), AvailableChildName = CharacterNames.Sophie, AvailableChild = new Child(), FriendshipSupportList = "Ryoma, Avatar, Jakob, Kaze", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Hana, Hinoka, Kagero, Oboro, Orochi, Rinkah, Sakura, Setsuna, Beruka, Camilla, Charlotte, Effie, Elise, Nyx, Peri, Selena, Avatar, Azura, Felicia, Mozu", RomanticSupports = new List<Character>() });
            list.Add(new Child { Name = CharacterNames.Sophie, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.Mischievous), StartingClass = classes.GetClassByClassName(ClassNames.Cavelier), AlternateClass = classes.GetClassByClassName(ClassNames.Mercenary), InheritanceA = new BaseClass(), InheritanceB = new BaseClass(), PrimaryParentName = CharacterNames.Silas, PrimaryParent = new Parent(), FriendshipSupportList = "Caeldori, Soleil, Velouria, Avatar", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Asugi, Hisame, Kiragi, Shiro, Forrest, Ignatius, Percy, Siegbert, Avatar, Kana, Dwyer, Shigure", RomanticSupports = new List<Character>() });
            list.Add(new Character { Name = CharacterNames.Shura, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.Highwayman), StartingClass = classes.GetClassByClassName(ClassNames.Outlaw), AlternateClass = classes.GetClassByClassName(ClassNames.Ninja), InheritanceA = classes.GetClassByClassName(ClassNames.Fighter), InheritanceB = new BaseClass(), FriendshipSupportList = CharacterNames.Avatar, FriendshipSupports = new List<Character>(), RomanticSupportsList = CharacterNames.Avatar, RomanticSupports = new List<Character>() });
            list.Add(new Character { Name = CharacterNames.Mozu, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.Forager), StartingClass = classes.GetClassByClassName(ClassNames.Villager), AlternateClass = classes.GetClassByClassName(ClassNames.Archer), InheritanceA = classes.GetClassByClassName(ClassNames.Apothecary), InheritanceB = classes.GetClassByClassName(ClassNames.Outlaw), FriendshipSupportList = "Oboro, Effie, Nyx, Avatar", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Azama, Hayato, Hinata, Kaden, Ryoma, Saizo, Subaki, Takumi, Arthur, Benny, Keaton, Laslow, Leo, Odin, Niles, Xander, Avatar, Jakob, Kaze, Silas", RomanticSupports = new List<Character>()});
            list.Add(new Character { Name = CharacterNames.Scarlet, AvailableOn = Path.Hoshido, PersonalSkill = classes.GetSkillByName(SkillNames.InExtremis), StartingClass = classes.GetClassByClassName(ClassNames.WyvernRider), AlternateClass = classes.GetClassByClassName(ClassNames.Outlaw), AlternateClassB = classes.GetClassByClassName(ClassNames.Knight), InheritanceA = classes.GetClassByClassName(ClassNames.SkyKnight), InheritanceB = classes.GetClassByClassName(ClassNames.SpearFighter), FriendshipSupportList = CharacterNames.Avatar, FriendshipSupports = new List<Character>(), RomanticSupportsList = CharacterNames.Avatar, RomanticSupports = new List<Character>() });
            list.Add(new Character { Name = CharacterNames.Izana, AvailableOn = Path.All, PersonalSkill = classes.GetSkillByName(SkillNames.Peacebringer), StartingClass = classes.GetClassByClassName(ClassNames.Monk), AlternateClass = classes.GetClassByClassName(ClassNames.Samurai), AlternateClassB = classes.GetClassByClassName(ClassNames.Apothecary), InheritanceA = new BaseClass(), InheritanceB = classes.GetClassByClassName(ClassNames.Mercenary), FriendshipSupportList = CharacterNames.Avatar, FriendshipSupports = new List<Character>(), RomanticSupportsList = CharacterNames.Avatar, RomanticSupports = new List<Character>() });
            list.Add(new Character { Name = CharacterNames.Rinkah, AvailableOn = Path.Hoshido, PersonalSkill = classes.GetSkillByName(SkillNames.FieryBlood), StartingClass = classes.GetClassByClassName(ClassNames.OniSavage), AlternateClass = classes.GetClassByClassName(ClassNames.Ninja), AlternateClassB = new BaseClass(), InheritanceA = classes.GetClassByClassName(ClassNames.Fighter), InheritanceB = classes.GetClassByClassName(ClassNames.Cavelier), FriendshipSupportList = "Kagero, Oboro, Orochi, Charlotte, Avatar", FriendshipSupports = new List<Character>(), RomanticSupportsList = "Azama, Hayato, Hinata, Kaden, Ryoma, Saizo, Subaki, Takumi, Benny, Keaton, Avatar, Jakob, Kaze, Silas", RomanticSupports = new List<Character>() });

            characters = list;
        }

        public Character GetCharacterByCharacterName(string name)
        {
            return characters.Where(o => o.Name == name).FirstOrDefault();
        }

        public List<string> GetCharacterNames()
        {
            List<string> list = new List<string>();

            list = characters.OrderBy(o => o.Name).Select(o => o.Name).ToList<string>();

            return list;
        }
    }
}