using ParingManager.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ParingManager.Models
{
    public class ClassModel
    {
        List<Class> classes;
        public SkillModel skills;

        public ClassModel()
        {
            classes = new List<Class>();
            skills = new SkillModel();
            LoadClasses();
        }

        private void LoadClasses()
        {
            List<Class> list = new List<Class>();

            list.Add(new BaseClass { Name = ClassNames.DarkPrincess, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_B, WeaponProficiency.Dragonstone_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Nobility), skills.GetSkillByName(SkillNames.DragonFang) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.HoshidoNoble + ", " + ClassNames.NohrNoble });
            list.Add(new PromotedClass { Name = ClassNames.HoshidoNoble, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_A, WeaponProficiency.Staff_B, WeaponProficiency.Dragonstone_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.DragonWard), skills.GetSkillByName(SkillNames.HoshidanUnity) }, PromotedFromList = ClassNames.DarkPrincess, PromotedFrom = new List<BaseClass>() });
            list.Add(new PromotedClass { Name = ClassNames.NohrNoble, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_A, WeaponProficiency.Tome_B, WeaponProficiency.Dragonstone_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.DraconicHex), skills.GetSkillByName(SkillNames.NohrianTrust) }, PromotedFromList = ClassNames.DarkPrincess, PromotedFrom = new List<BaseClass>() });
            list.Add(new SpecialClass { Name = ClassNames.Songstress, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_C }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Luck4), skills.GetSkillByName(SkillNames.InspiringSong), skills.GetSkillByName(SkillNames.VoiceOfPeace), skills.GetSkillByName(SkillNames.ForeignPrincess) }, CanPassDown = false });
            list.Add(new SpecialClass { Name = ClassNames.DreadFighter, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_A, WeaponProficiency.Axe_B, WeaponProficiency.Dagger_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.EvenKeel), skills.GetSkillByName(SkillNames.IronWill), skills.GetSkillByName(SkillNames.Clarity), skills.GetSkillByName(SkillNames.Aggressor) }, CanPassDown = false });
            list.Add(new SpecialClass { Name = ClassNames.DarkFalcon, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_B, WeaponProficiency.Tome_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Speed2), skills.GetSkillByName(SkillNames.Relief), skills.GetSkillByName(SkillNames.RallyMovement), skills.GetSkillByName(SkillNames.Galeforce) }, CanPassDown = false });
            list.Add(new BaseClass { Name = ClassNames.Samurai, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_B }, Skills = new List<Skill> {skills.GetSkillByName(SkillNames.DuelistsBlow), skills.GetSkillByName(SkillNames.Vantage) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Swordmaster + ", " + ClassNames.MasterOfArms });
            list.Add(new PromotedClass { Name = ClassNames.Swordmaster, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Astra), skills.GetSkillByName(SkillNames.Swordfaire) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Samurai });
            list.Add(new PromotedClass { Name = ClassNames.MasterOfArms, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_A, WeaponProficiency.Spear_B, WeaponProficiency.Axe_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.SealStrength), skills.GetSkillByName(SkillNames.LifeAndDeath) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Samurai + ", " + ClassNames.Villager });
            list.Add(new BaseClass { Name = ClassNames.Villager, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_C }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Aptitude), skills.GetSkillByName(SkillNames.Underdog) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.MasterOfArms + ", " + ClassNames.Merchant });
            list.Add(new PromotedClass { Name = ClassNames.Merchant, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_B, WeaponProficiency.Bow_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Profiteer), skills.GetSkillByName(SkillNames.Spendthrift) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Villager + ", " + ClassNames.Apothecary });
            list.Add(new BaseClass { Name = ClassNames.Apothecary, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Bow_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.PotentPotion), skills.GetSkillByName(SkillNames.QuickSalve) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Merchant + ", " + ClassNames.Mechanist });
            list.Add(new PromotedClass { Name = ClassNames.Mechanist, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Dagger_A, WeaponProficiency.Bow_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Golembane), skills.GetSkillByName(SkillNames.Replicate) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Apothecary + ", " + ClassNames.Ninja });
            list.Add(new BaseClass { Name = ClassNames.Ninja, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Dagger_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Locktouch), skills.GetSkillByName(SkillNames.PoisonStrike) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.MasterNinja + ", " + ClassNames.Mechanist });
            list.Add(new PromotedClass { Name = ClassNames.MasterNinja, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_B, WeaponProficiency.Dagger_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Lethality), skills.GetSkillByName(SkillNames.Shurikenfaire) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Ninja });
            list.Add(new BaseClass { Name = ClassNames.OniSavage, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Axe_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.SealResistance), skills.GetSkillByName(SkillNames.Shove) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.OniSavage + ", " + ClassNames.Blacksmith });
            list.Add(new PromotedClass { Name = ClassNames.OniChieftain, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Axe_A, WeaponProficiency.Tome_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.DeathBlow), skills.GetSkillByName(SkillNames.Counter) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.OniSavage });
            list.Add(new PromotedClass { Name = ClassNames.Blacksmith, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Axe_A, WeaponProficiency.Sword_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.SalvageBlow), skills.GetSkillByName(SkillNames.Lancebreaker) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.OniSavage });
            list.Add(new BaseClass { Name = ClassNames.SpearFighter, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.SealDefense), skills.GetSkillByName(SkillNames.Swap) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.SpearMaster + ", " + ClassNames.Basara });
            list.Add(new PromotedClass { Name = ClassNames.SpearMaster, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.SealSpeed), skills.GetSkillByName(SkillNames.Lancefaire) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.SpearFighter });
            list.Add(new PromotedClass { Name = ClassNames.Basara, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_A, WeaponProficiency.Tome_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.RendHeaven), skills.GetSkillByName(SkillNames.Quixotic) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.SpearFighter + ", " + ClassNames.Diviner });
            list.Add(new BaseClass { Name = ClassNames.Diviner, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Tome_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Magic2), skills.GetSkillByName(SkillNames.FutureSight) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Basara + ", " + ClassNames.Onmyoji });
            list.Add(new PromotedClass { Name = ClassNames.Onmyoji, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Tome_A, WeaponProficiency.Staff_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.RallyMagic), skills.GetSkillByName(SkillNames.Tomefaire) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Diviner + ", " + ClassNames.ShrineMaiden });
            list.Add(new BaseClass { Name = ClassNames.ShrineMaiden, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Staff_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Miracle), skills.GetSkillByName(SkillNames.RallyLuck) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Onmyoji + ", " + ClassNames.Priestess });
            list.Add(new BaseClass { Name = ClassNames.Monk, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Staff_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Miracle), skills.GetSkillByName(SkillNames.RallyLuck) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Onmyoji + ", " + ClassNames.GreatMaster });
            list.Add(new PromotedClass { Name = ClassNames.GreatMaster, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_B, WeaponProficiency.Staff_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Renewal), skills.GetSkillByName(SkillNames.Countermagic) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Monk });
            list.Add(new PromotedClass { Name = ClassNames.Priestess, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Bow_B, WeaponProficiency.Staff_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Renewal), skills.GetSkillByName(SkillNames.Countermagic) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.ShrineMaiden });
            list.Add(new BaseClass { Name = ClassNames.SkyKnight, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.DartingBlow), skills.GetSkillByName(SkillNames.Camaraderie) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.FalconKnight + ", " + ClassNames.KinshiKnight });
            list.Add(new PromotedClass { Name = ClassNames.FalconKnight, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_A, WeaponProficiency.Staff_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.RallySpeed), skills.GetSkillByName(SkillNames.WardingBlow) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.SkyKnight });
            list.Add(new PromotedClass { Name = ClassNames.KinshiKnight, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_B, WeaponProficiency.Bow_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.AirSuperiority), skills.GetSkillByName(SkillNames.Amaterasu) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.SkyKnight + ", " + ClassNames.Archer });
            list.Add(new BaseClass { Name = ClassNames.Archer, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Bow_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Skill2), skills.GetSkillByName(SkillNames.QuickDraw) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Sniper + ", " + ClassNames.KinshiKnight });
            list.Add(new PromotedClass { Name = ClassNames.Sniper, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Bow_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.CertainBlow), skills.GetSkillByName(SkillNames.Bowfaire) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Archer });
            list.Add(new BaseClass { Name = ClassNames.Kitsune, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Beaststone_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Evenhanded), skills.GetSkillByName(SkillNames.Beastbane) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.NineTails });
            list.Add(new PromotedClass { Name = ClassNames.NineTails, Proficiencies =  new List<WeaponProficiency> { WeaponProficiency.Beaststone_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.EvenBetter), skills.GetSkillByName(SkillNames.GrislyWound) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Kitsune });
            list.Add(new BaseClass { Name = ClassNames.Cavelier, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_B, WeaponProficiency.Spear_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.ElbowRoom), skills.GetSkillByName(SkillNames.Shelter) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Paladin + ", " + ClassNames.GreatKnight });
            list.Add(new PromotedClass { Name = ClassNames.Paladin, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_A, WeaponProficiency.Spear_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Defender), skills.GetSkillByName(SkillNames.Aegis) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Cavelier });
            list.Add(new PromotedClass { Name = ClassNames.GreatKnight, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_B, WeaponProficiency.Spear_A, WeaponProficiency.Axe_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Luna), skills.GetSkillByName(SkillNames.ArmoredBlow) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Cavelier + ", " + ClassNames.Knight });
            list.Add(new BaseClass { Name = ClassNames.Knight, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Defense2), skills.GetSkillByName(SkillNames.NaturalCover) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.General + ", " + ClassNames.GreatKnight });
            list.Add(new PromotedClass { Name = ClassNames.General, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Spear_A, WeaponProficiency.Axe_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.WaryFighter), skills.GetSkillByName(SkillNames.Pavise) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Knight });
            list.Add(new BaseClass { Name = ClassNames.Fighter, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Axe_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.HP5), skills.GetSkillByName(SkillNames.Gamble) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Berserker + ", " + ClassNames.Hero });
            list.Add(new PromotedClass { Name = ClassNames.Berserker, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Axe_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.RallyStrength), skills.GetSkillByName(SkillNames.Axefaire) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Fighter });
            list.Add(new PromotedClass { Name = ClassNames.Hero, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_A, WeaponProficiency.Axe_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Sol), skills.GetSkillByName(SkillNames.Axebreaker) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Fighter + ", " + ClassNames.Mercenary });
            list.Add(new BaseClass { Name = ClassNames.Mercenary, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.GoodFortune), skills.GetSkillByName(SkillNames.StrongRiposte) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Hero + ", " + ClassNames.BowKnight });
            list.Add(new PromotedClass { Name = ClassNames.BowKnight, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_B, WeaponProficiency.Bow_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.RallySkill), skills.GetSkillByName(SkillNames.Shurikenbreaker) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Mercenary + ", " + ClassNames.Outlaw });
            list.Add(new BaseClass { Name = ClassNames.Outlaw, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Bow_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Locktouch), skills.GetSkillByName(SkillNames.Movement1) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Adventurer + ", " + ClassNames.BowKnight });
            list.Add(new PromotedClass { Name = ClassNames.Adventurer, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Bow_A, WeaponProficiency.Staff_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.LuckySeven), skills.GetSkillByName(SkillNames.Pass) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Outlaw });
            list.Add(new BaseClass { Name = ClassNames.WyvernRider, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Axe_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Strength2), skills.GetSkillByName(SkillNames.Lunge) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.WyvernLord + ", " + ClassNames.MaligKnight });
            list.Add(new PromotedClass { Name = ClassNames.WyvernLord, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Axe_A, WeaponProficiency.Spear_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.RallyDefense), skills.GetSkillByName(SkillNames.Swordbreaker) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.WyvernRider });
            list.Add(new PromotedClass { Name = ClassNames.MaligKnight, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Axe_A, WeaponProficiency.Tome_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.SavageBlow), skills.GetSkillByName(SkillNames.Trample) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.WyvernRider });
            list.Add(new BaseClass { Name = ClassNames.DarkMage, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Tome_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Heartseeker), skills.GetSkillByName(SkillNames.MaleficAura) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Sorceror + ", " + ClassNames.DarkKnight });
            list.Add(new PromotedClass { Name = ClassNames.Sorceror, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Tome_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Vengeance), skills.GetSkillByName(SkillNames.Bowbreaker }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.DarkMage });
            list.Add(new PromotedClass { Name = ClassNames.DarkKnight, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Sword_B, WeaponProficiency.Tome_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.SealMagic), skills.GetSkillByName(SkillNames.Lifetaker) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.DarkMage });
            list.Add(new BaseClass { Name = ClassNames.Troubadour, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Staff_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Resistance2), skills.GetSkillByName(SkillNames.Gentilhomme) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Strategist + ", " + ClassNames.Butler });
            list.Add(new PromotedClass { Name = ClassNames.Strategist, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Tome_B, WeaponProficiency.Staff_A }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.RallyResistance), skills.GetSkillByName(SkillNames.Inspiration) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Troubadour });
            list.Add(new PromotedClass { Name = ClassNames.Butler, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Dagger_B, WeaponProficiency.Staff_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.LiveToServe), skills.GetSkillByName(SkillNames.Tomebreaker) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Troubadour });
            list.Add(new BaseClass { Name = ClassNames.Wolfskin, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Beaststone_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.OddShaped), skills.GetSkillByName(SkillNames.Beastbane) }, PromotesTo = new List<PromotedClass>(), PromotesToList = ClassNames.Wolfssegner });
            list.Add(new PromotedClass { Name = ClassNames.Wolfssegner, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Beaststone_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.BetterOdds), skills.GetSkillByName(SkillNames.GrislyWound) }, PromotedFrom = new List<BaseClass>(), PromotedFromList = ClassNames.Wolfskin });
            list.Add(new SpecialClass { Name = ClassNames.Ballistician, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Bow_B }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Survey), skills.GetSkillByName(SkillNames.OpportunityShot), skills.GetSkillByName(SkillNames.RifledBarrel), skills.GetSkillByName(SkillNames.Surefooted) }, CanPassDown = false });
            list.Add(new SpecialClass { Name = ClassNames.Witch, Proficiencies = new List<WeaponProficiency> { WeaponProficiency.Tome_S }, Skills = new List<Skill> { skills.GetSkillByName(SkillNames.Shadowgift), skills.GetSkillByName(SkillNames.WitchsBrew), skills.GetSkillByName(SkillNames.Warp), skills.GetSkillByName(SkillNames.ToxicBrew) }, CanPassDown = false });

            classes = list;
        }

        public Class GetClassByClassName(string name)
        {
            return classes.Where(o => o.Name == name).FirstOrDefault();
        }

        public List<string> GetClassNames()
        {
            List<string> list = new List<string>();

            list = classes.OrderBy(o => o.Name).Select(o => o.Name).ToList<string>();

            return list;
        }
    }
}